### ISSUE TITLE
Error Deploying Kronos on dev-cluster as part of e2e deployment script

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/fabric8-analytics-stack-analysis#186]
As per this housekeeping issue: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1151
@jchevret 's observation:
Looks like the problem is that the livenesscheck is failing and thus the container is killed and restarted
Livenesscheck is: http-get http://:6006/
Could it be that the kronos/gunicorn service is failing to start properly?
Doing a curl to :6006 from the node the pod is running on ...  one see's
`curl: (56) Recv failure: Connection reset by peer`

So the process listening on port 6006 receives the connection but crashes for some reason and never returns a response
So:
    network from the nodes to the pod works
    network from the container out works
    node can't complete the liveness check for the kronos container, and thus the container is restarted X times before the deployment times out completely
IMO the next steps would be to understand why the kronos service (gunicorn) won't respond to requests sent to http://:6006

**Comment by sara-02** [comment]
It seems as if the the current `initaldelay` time is too short, the AWS is taking approx 2-5 mins to return the data.
@msrb are the probes checked as soon as the REST API comes up, or does it wait for the inital data load to take place?

**Comment by msrb** [comment]
Let me try to reproduce this.

@sara-02 in the mean time, did you spot anything interesting in the logs?

**Comment by msrb** [comment]
The [initialDelaySeconds](https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/blob/62ce2459e8ce4d852305e868b0f9a18e2b2b1ca7/openshift/template.yaml#L69) may seem low (15s), but it is compensated by quite generous [timeoutSeconds](https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/blob/62ce2459e8ce4d852305e868b0f9a18e2b2b1ca7/openshift/template.yaml#L71) (30s) and [periodSeconds](https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/blob/62ce2459e8ce4d852305e868b0f9a18e2b2b1ca7/openshift/template.yaml#L70) (60s) which give the service enough time to actually start. I think that's why the same health check configuration works in staging and prod.

I think the real problem is somewhere else. This service can be quite memory demanding and the default request and limit is just [512MiB](https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/blob/62ce2459e8ce4d852305e868b0f9a18e2b2b1ca7/openshift/template.yaml#L105-L115). Production and staging deployments [override these values](https://github.com/openshiftio/saas-analytics/blob/master/bay-services/kronos.yaml#L30-L31).

We should also lower request/limit for CPU as it seems to be unreasonably high for development deployments.

I was able to successfully deploy the service on dev cluster when I increased the memory request/limit (1024/1536MiB) and lowered the CPU request/limit to just 1000m. I also stopped seeing the "Pod sandbox changed, it will be killed and re-created" error when I did that.
